#pragma once

#define PT_ERROR_NONE				BYTE(0x00)
#define PT_ERROR_USER_EXIST			BYTE(0x01)
#define PT_ERROR_USER_NOT_FOUND		BYTE(0x02)
#define PT_ERROR_USER_CERT_FAILED	BYTE(0x03)
#define PT_ERROR_INVALID_VERSION	BYTE(0x04)
#define PT_ERROR_UNREGIST_FAILED	BYTE(0x05)